# Generated by Django 3.1.2 on 2020-10-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_id',
            new_name='id',
        ),
    ]
