# Generated by Django 3.1.2 on 2020-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_offer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(default=1, upload_to='artist'),
            preserve_default=False,
        ),
    ]
